from kivy_reserved_words.classes.Button_Self import run_button_self
from kivy_reserved_words.classes.Button_Root import run_button_root
from kivy_reserved_words.classes.Button_App import run_button_app
from kivy_reserved_words.classes.Button_Args import run_button_args
from kivy_reserved_words.classes.Button_Id import run_button_id
from kivy_reserved_words.classes.Button_Ids import run_button_ids
from kivy_reserved_words.classes.Simpl_Calc import run_simpl_calc
from kivy_reserved_words.classes.Button_If import run_button_if